services:
  rimafon-main-page:
    container_name: rimafon-main-page
    image: nginx:alpine
    networks:
      - nginx-proxy
    restart: unless-stopped
    volumes:
      - ./index:/usr/share/nginx/html

networks:
  nginx-proxy:
    external: true
